kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag-aug12-1-vllm-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rag-aug12-1-vllm-dsp-job
    namespace: rag-aug12-1-vllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag-aug12-1-vllm-dsp-job-role